apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-lab-webapp.name" . }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "k8s-lab-webapp.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "k8s-lab-webapp.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: APP_VERSION
              value: {{ .Values.backend.appVersion | quote }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: {{ include "k8s-lab-webapp.name" . }}-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
