apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-lab-webapp.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8s-lab-webapp.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "k8s-lab-webapp.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-lab-webapp.name" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "k8s-lab-webapp.name" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}