apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-lab-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-lab-frontend
  template:
    metadata:
      labels:
        app: k8s-lab-frontend
    spec:
      containers:
        - name: frontend
          image: k8s-lab-frontend:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-lab-frontend
spec:
  selector:
    app: k8s-lab-frontend
  ports:
    - port: 80
      targetPort: 80
