backend:
  image:
    repository: dovanminh98/k8s-lab-backend
    tag: "1.0.0"
    pullPolicy: IfNotPresent

frontend:
  image:
    repository: dovanminh98/k8s-lab-frontend
    tag: "1.0.0"
    pullPolicy: IfNotPresent