apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-lab-webapp
  namespace: lab
spec:
  project: default
  source:
    repoURL: https://github.com/minhdevops/k8s-lab-webapp.git
    targetRevision: HEAD
    path: helm/k8s-lab-webapp
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
